/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        backgrounddefault: "var(--backgrounddefault)",
        backgroundmuted: "var(--backgroundmuted)",
        "backgroundmuted-2": "var(--backgroundmuted-2)",
        "backgroundmuted-hover": "var(--backgroundmuted-hover)",
        backgroundprimary: "var(--backgroundprimary)",
        "backgroundprimary-hover": "var(--backgroundprimary-hover)",
        backgroundsecondary: "var(--backgroundsecondary)",
        "backgroundsecondary-hover": "var(--backgroundsecondary-hover)",
        borderdefault: "var(--borderdefault)",
        borderinverse: "var(--borderinverse)",
        icondefault: "var(--icondefault)",
        iconinverse: "var(--iconinverse)",
        textdefault: "var(--textdefault)",
        textinverse: "var(--textinverse)",
        "textinverse-muted": "var(--textinverse-muted)",
        textmuted: "var(--textmuted)",
      },
      fontFamily: {
        "heading-h1": "var(--heading-h1-font-family)",
        "heading-h1-italic": "var(--heading-h1-italic-font-family)",
        "heading-h1-uppercase": "var(--heading-h1-uppercase-font-family)",
        "heading-h2": "var(--heading-h2-font-family)",
        "heading-h2-italic": "var(--heading-h2-italic-font-family)",
        "heading-h2-uppercase": "var(--heading-h2-uppercase-font-family)",
        "heading-h3": "var(--heading-h3-font-family)",
        "heading-h3-italic": "var(--heading-h3-italic-font-family)",
        "heading-h3-uppercase": "var(--heading-h3-uppercase-font-family)",
        "heading-h4": "var(--heading-h4-font-family)",
        "heading-h4-italic": "var(--heading-h4-italic-font-family)",
        "heading-h4-uppercase": "var(--heading-h4-uppercase-font-family)",
        "heading-h5": "var(--heading-h5-font-family)",
        "heading-h5-italic": "var(--heading-h5-italic-font-family)",
        "heading-h5-uppercase": "var(--heading-h5-uppercase-font-family)",
        "heading-h6": "var(--heading-h6-font-family)",
        "heading-h6-italic": "var(--heading-h6-italic-font-family)",
        "heading-h6-uppercase": "var(--heading-h6-uppercase-font-family)",
        "heading-large": "var(--heading-large-font-family)",
        "heading-large-italic": "var(--heading-large-italic-font-family)",
        "heading-medium": "var(--heading-medium-font-family)",
        "heading-medium-italic": "var(--heading-medium-italic-font-family)",
        "heading-small": "var(--heading-small-font-family)",
        "heading-small-italic": "var(--heading-small-italic-font-family)",
        "heading-xlarge": "var(--heading-xlarge-font-family)",
        "heading-xlarge-italic": "var(--heading-xlarge-italic-font-family)",
        "text-default": "var(--text-default-font-family)",
        "text-large": "var(--text-large-font-family)",
        "text-medium": "var(--text-medium-font-family)",
        "text-meta": "var(--text-meta-font-family)",
        "text-meta-large": "var(--text-meta-large-font-family)",
        "text-meta-small": "var(--text-meta-small-font-family)",
        "text-small": "var(--text-small-font-family)",
        "text-xlarge": "var(--text-xlarge-font-family)",
        "text-xsmall": "var(--text-xsmall-font-family)",
      },
    },
  },
  plugins: [],
}